/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author JHON
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMascota
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnFamilias = new javax.swing.JButton();
        btnPersonas = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnMascotas = new javax.swing.JButton();
        btnRegistrarCita = new javax.swing.JButton();
        btnInyeccion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        Icono1 = new javax.swing.JLabel();
        Icono2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(227, 244, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Usuario:");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("PetCare");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huella.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario.setText("jLabel1");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 40));

        btnFamilias.setBackground(new java.awt.Color(62, 172, 235));
        btnFamilias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFamilias.setForeground(new java.awt.Color(255, 255, 255));
        btnFamilias.setText("Familias");
        btnFamilias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamiliasActionPerformed(evt);
            }
        });
        jPanel2.add(btnFamilias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 100, -1));

        btnPersonas.setBackground(new java.awt.Color(62, 172, 235));
        btnPersonas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonas.setText("Personas");
        jPanel2.add(btnPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, -1));

        btnEmpleados.setBackground(new java.awt.Color(62, 172, 235));
        btnEmpleados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setText("Empleados");
        jPanel2.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 100, -1));

        btnMascotas.setBackground(new java.awt.Color(62, 172, 235));
        btnMascotas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMascotas.setForeground(new java.awt.Color(255, 255, 255));
        btnMascotas.setText("Mascotas");
        jPanel2.add(btnMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 110, -1));

        btnRegistrarCita.setBackground(new java.awt.Color(62, 172, 235));
        btnRegistrarCita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarCita.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarCita.setText("Citas");
        jPanel2.add(btnRegistrarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 110, -1));

        btnInyeccion.setBackground(new java.awt.Color(62, 172, 235));
        btnInyeccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInyeccion.setForeground(new java.awt.Color(255, 255, 255));
        btnInyeccion.setText("Inyecciones");
        jPanel2.add(btnInyeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 110, -1));

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Cerrar Sesion");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 130, -1));

        Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono2.png"))); // NOI18N
        jPanel2.add(Icono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 130, 140));

        Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono1.png"))); // NOI18N
        jPanel2.add(Icono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 120, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnFamiliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamiliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFamiliasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono1;
    private javax.swing.JLabel Icono2;
    public javax.swing.JButton btnEmpleados;
    public javax.swing.JButton btnFamilias;
    public javax.swing.JButton btnInyeccion;
    public javax.swing.JButton btnMascotas;
    public javax.swing.JButton btnPersonas;
    public javax.swing.JButton btnRegistrarCita;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
